server:
  port: 9000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

eureka:
  #instance:
  #  preferIpAddress: true
  client:
     enabled: false
    #registerWithEureka: true
    #fetchRegistry: true
    #serviceUrl:
    #  defaultZone: http://${DISCOVERY_HOST}:9761/eureka/

logging:
  level:
    ROOT: info
    com.jade.platform: INFO

spring:
  cloud:
    function:
      definition: mailing; lookup; billing
    stream:
      bindings:
        mailing-in-0:
          destination: mailing-send
  rabbitmq:
    host: ${BROKER_HOST}
    port: 5672
    username: guest
    password: guest
    virtual-host: /

sms:
  twilio:
    account_sid: "{cipher}fd7dac9b4821bbd18ce9ee4e6327d22ed94e278eac477586ea5e02bc829e2c2031f584c1888fe413f4da5d89a777136b11ce369d3fa9b671fe591fbc301395bc"
    auth_token: "{cipher}29439e7e8f5b7c02eaf28767dbffa4052931813b23996a8b1a1b093cf766a899a0121d00c66eb15c3b8a92e988590de77c7759c57c1fb4805c63065f1ebd4c5b"
    sender_name: ThamaniInvest


send:
   grid:
      url: https://api.sendgrid.com/v3/mail/send
      apiKey: "{cipher}5fe7843af003cd0f33ee9d3f0434de6df2e5a75284848c0466a561273228c94bdab53aa316b78640d6aff34ac1c72480142ba5a8491436d380c7f1aa87c23ce86374bd4fa49212187d5ddb5c009f2fb06f94fb4302aa59005d4225b02c612bea"
      from: no-reply@meld-tech.com

post:
   mark:
      url: https://api.postmarkapp.com/email/withTemplate
      server-token: 1bf07dec-09c8-45a5-a1ec-528573777c5f

provider:
   active: POST_MARK

management:
  endpoints:
    web:
      exposure:
        include: "*"

