server:
  port: 9011

logging:
  level:
    ROOT: ${ROOT_LOG_LEVEL}
    com.jade.platform: ${LOG_LEVEL}
    org.springframework.security: ${LOG_LEVEL}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/user_service?serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: "{cipher}956bf7ce65e62326d2d1b9ad72f9cd1cc096159aafd25e88957d7c43711058f6"
#    password: "{cipher}94433f0966a6cd4aea5407ef962e1d2231c6154ea4405c273ef82ee728b43817"
    username: ${USERNAME}
    password: ${PASSWORD}
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  jpa:
    open-in-view: off

app:
  password:
    strength: 11
  login:
    url: ${LOGIN_URL}
  logout:
    url: ${LOGOUT_URL}
issuer:
  uri: ${ISSUER_HOST_URL}
private:
  key: jadedemo.jks

authentication:
   not_found:
       path: ${NOT_FOUND_PATH}

key:
  password: "{cipher}634898ab430a02301ac5e22e27e90a2fea5cad5f6580bfd80d9258cb2fcadb3a"
  alias: "{cipher}d3fac537035e9e22b4fcf7507698119228bc8f4d6c7bf4d98e5f3aab3f88670c"

management:
  endpoints:
    web:
      exposure:
        include: "*"
