server:
  port: 9300

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST}:9761/eureka/

logging:
  level:
    ROOT: INFO
    com.tima.platform: DEBUG


spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}?stringtype=unspecified&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    name: agency_service
    username: "{cipher}082341d46af4f5d7e5749d7013a1a6bb076be928b7829fa983292e3a15f2ab42"
    password: "{cipher}19a959f0e4fa9f132df80a66e9f3cddf7caf37b24b034aa89d0e0618a959fe2b"
  devtools:
    restart.enabled: true
  pool:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URI}/.well-known/authorization-server/jwks.json
  cloud:
    function:
      definition: alert
    stream:
      bindings:
        alert-in-0:
          destination: alert-notice
  rabbitmq:
    host: ${BROKER_HOST}
    port: 5672
    username: guest
    password: guest
    virtual-host: /


app:
   scheduler:
      campaign:
         status: '0 30 0 * * ?' 

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    rabbit:
      enabled: true

