spring:
  application:
    name: stake-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT:5432}/stake_service?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: "{cipher}8283992cfdd36c80d5865a47922662fc5551b7522d5b0010aae0393a09a90bf8"
    password: "{cipher}7bb75a1d16f037829e7507739a950be52ca01ab16268bf48d81e7962daee6e20"
    # R2DBC connection pool settings
    pool:
      initial-size: 5
      max-size: ${stake.platform.database.max-pool-size}
      max-idle-time: 30m
      validation-query: SELECT 1
      max-create-connection-time: 10s
      max-acquire-time: 5s
      max-life-time: 1h
  liquibase:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/stake_service
      user: "{cipher}8283992cfdd36c80d5865a47922662fc5551b7522d5b0010aae0393a09a90bf8"
      password: "{cipher}7bb75a1d16f037829e7507739a950be52ca01ab16268bf48d81e7962daee6e20"
      change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
      open-in-view: false
  pool:
    enabled: true

server:
  port: 9900

  # Redis configuration
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    database: 0
    ssl: false
    connect-timeout: 2s
    command-timeout: 1s
    # Redis connection pool settings
    pool:
      max-total: 16
      max-idle: 8
      min-idle: 4
      max-wait-time: 2s
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs: 30s
  lettuce:
    pool:
      max-active: 16
      max-idle: 8
      min-idle: 4
      max-wait: 2000ms
      time-between-eviction-runs: 30s
    shutdown-timeout: 2000ms
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true

stake:
  platform:
    database:
      schema: public
      max-pool-size: 10
    security:
      api-key: ${API_KEY:default-local-env}
      token-expiry-seconds: 3600

#  Stake API Service Configuration
stake-api:
  api:
    version: v1
    base-path: /api
  security:
    api-key-auth-enabled: true
    api-key-header: X-API-Key
  rate-limit:
    enabled: true
    default-capacity: 100
    default-refill-period: 60
    ip-capacity: 60
    ip-refill-period: 60


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{requestId}] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOG_LEVEL}
    org.meldtech.platform: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data: INFO
    org.springframework.data.redis: INFO
    io.r2dbc: INFO
    io.lettuce.core: INFO
    reactor.netty: INFO

  file:
    name: logs/stake-service.log
    max-size: 10MB
    max-history: 7
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB
