server:
  port: 9100

mail:
  otp:
    template: d-51f59b90307f43518af1ff015950028c 
  reset:
    password:
      template: d-3925528782334bc0947b33f4df53c4af

springdoc:
  server-url: ${SWAGGER_DOC_URL}
  swagger-ui:
    tagsSorter: alpha
  writer-with-order-by-keys: true


spring:
  profiles:
    include: #dev, doc_dev #users, documents
  codec:
    max-in-memory-size: 7048576
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${ISSUER_HOST}/.well-known/authorization-server/jwks.json

auth:
  config:
     disabled: true
