spring:
  application:
    name: user-service-lib
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}?user_service?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: "{cipher}956bf7ce65e62326d2d1b9ad72f9cd1cc096159aafd25e88957d7c43711058f6"
    password: "{cipher}4dfadcdf65515adf7b9c9446ff5bec6da100e0867894508126bc4cc164449554"
    name: user_service
  devtools:
    restart.enabled: true
  pool:
    enabled: true

  cloud:
    function:
      definition: mailing; setting; updatePaymentStatus; updateCompanyEmail; reminderData
    stream:
      bindings:
        mailing-out-0:
          destination: mailing-send
        userIndustry-out-0:
          destination: userIndustry
        setting-in-0:
          destination: notice-setting
        updatePaymentStatus-in-0:
           destination: updatePaymentStatus
        updatePaymentStatus-out-0:
           destination: updatePaymentStatus
        updateCompanyEmail-in-0:
           destination: updateCompanyEmail
        updateCompanyEmail-out-0:
           destination: updateCompanyEmail
        reminderData-out-0:
           destination: reminderData
        reminderData-in-0:
           destination: reminderData

  rabbitmq:
    host: ${BROKER_HOST}
    port: 5672
    username: guest

email:
  activation:
    template: 38483102
  password-reset:
    template: 38490009
  verification:
      link: http://13.244.112.165/verify/email/otp
  enforcer: gamingcommission@enugustate.gov.ng
meld:
  scheduler:
    token:
      cleanup: '0 0 */3 * * ?'
    otp:
      cleanup: '0 0 * * * ?'
    payment:
       retry: '0 0 * * * ?'
       cleanup: '0 15 */12 * * ?'
       hourUnit: 24
       daysUnit: 8
    application:
       cleanup: '0 15 */02 * * ?'
       reminder:
           setting: '0 15 */07: * * ?'
           duration: 7
           penalty: 14

oauth2:
  client:
    id: "{cipher}d3242bdde7c9024fb963ec6e9b644d0bd9b0d613bd8ace1007e87e9a0e888512a54b9c2c0d9c96fa06bb2a58ba1abe6fee7f5dcf95afd3da54bd13c3df6c5415"
    secret:  "{cipher}0a737da608e28c5291b75c297c8bba13676c9059b2537883ca5180809abc2dd9"

  authorize:
    url: ${ISSUER_HOST}/oauth2/authorize
    scope: ${SCOPE}
    challengeMethod: S256

  authorization:
    url: ${ISSUER_HOST}/oauth2/token
    grant_type: authorization_code
    redirect_uri: ${REDIRECT_URL}

  logout:
    url: ${ISSUER_HOST}/logout

cloudinary:
  cloud-name: "{cipher}8983718db7b86f9c705103f0e1e7ff52cb260de1269cfddfe3d6e6483816c292"
  api-key: "{cipher}d040cb0b61a270e1d00be3e6cfbaba94037c92d4c278030ce8bf41b8e70d3fd3"
  api-secret: "{cipher}e66d5a1b4e5de8d26ed5d1fb170d0c221adc162735363560ff136fb37c7e9a60120ba45aff9f0ecc6c7d8cd75c270f00"

verification:
   company:
      url: https://api.qoreid.com/v1/ng/identities/cac-basic
   agent:
      url: https://api.qoreid.com/v1/ng/identities/nin/
   clientId: "{cipher}61c44c95eb6be96f5801d153711109ffa97d50406b941998dbe87e5fbdcec991d30d79687291fe92e00d838f85d31b8f"
   secret: "{cipher}4c309408a1557ae0115c6e4878d373e3cd4e2eb9b9bbe9f32cc790aad19e1f2486f0d31518e1657d8613b9bd0416ae5f732019e41f43b30059363bb4d758f8f6"
   auth:
     url: https://api.qoreid.com/token

payment:
   remita:
      url: https://login.remita.net/remita/exapp/api/v1/send/api/echannelsvc/merchant/api/paymentinit
      status: 
         url: https://login.remita.net/remita/exapp/api/v1/send/api/echannelsvc
      merchantId: "{cipher}c1617efbf1f8fdff78e3648db57f66ddf274786318c1da68031360e9278ec733"
      apiKey: "{cipher}2914c2f6fe4e1cb6f8a4b8aeea314f0511e9847cd9250bef0c74aa32530601b3"
      serviceTypeId: "{cipher}c1604a871e49e17bec05b8c46251b711bb439a042bffec578d7fc0a40cdd7c8b"

report:
  logo:
    path: https://assets.maccarianagency.com/backgrounds/img18.jpg
  date:
    format: "dd MMMM yyyy HH:mm:ss"
  download:
    path: "./download.pdf"
  author: "Meld Technologies"
  subject: "Meld Technologies Report Generation Tool"

logging:
  level:
    root: ${ROOT_LOG_LEVEL}

