server:
  port: 9001

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST}:9761/eureka/

logging:
  level:
    ROOT: info
    com.tima.platform: INFO


spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}?stringtype=unspecified&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    name: user_service
    username: "{cipher}082341d46af4f5d7e5749d7013a1a6bb076be928b7829fa983292e3a15f2ab42"
    password: "{cipher}19a959f0e4fa9f132df80a66e9f3cddf7caf37b24b034aa89d0e0618a959fe2b"
  devtools:
    restart.enabled: true
  pool:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URI}/.well-known/authorization-server/jwks.json
  cloud:
    function:
      definition: mailing; setting
    stream:
      bindings:
        mailing-out-0:
          destination: mailing-send
        userIndustry-out-0:
          destination: userIndustry
        setting-in-0:
          destination: notice-setting
  rabbitmq:
    host: ${BROKER_HOST}
    port: 5672
    username: guest
    password: guest
    virtual-host: /

email:
  activation:
    template: d-3eca4131b71949989a5d9ee7b1993511
  password-reset:
    template: d-1a0862c51bcd47dbabae68a3fa380967

app:
  scheduler:
    token:
      cleanup: '0 0 */3 * * ?'
    otp:
      cleanup: '0 0 * * * ?'

tima:
  client:
    scope: USER-STANDARD
    secret: "{cipher}846f15e6f8fce9c2deeb67d686c734d9ee7b058b7fe45d0f538e77b1fdd4e956"
    id: "{cipher}dd3c5e7d28a8b97b8cce221fb0f613760b6086626f415f9dd034d57f26ed439e16f3ec380fa57a1b4ac0924adebcdc1c"
  auth:
    server:
      url: http://${AUTH_SERVICE}:9011/oauth2/token
  key: "{cipher}3c14bf6fd7fc24a6596870906a1a1362ca6f3cf6cbe62692b7fb4ea102f6e86f2f11d00f57efc908ac0c626df0cb39257c3230f2410847588aa6253b00605b10"
  iv: "{cipher}ea76dce425827e48f98e0a85af253d67225cdbae4e55046250250915dcd5a26257119e1b1632ec7f0b1157c845352417"

aws:
  s3:
      key:
          access: "{cipher}7308769c880d44773d73dbc0369c966b5ea54e55d14fb68603850fd544d8f5fda24410a25ac1c1b79739fb1c920647ca"
          secret: "{cipher}c24f4eff9cdfc4ec2a13177c0c1ee782fde0d456093eece3d3d8575ef30831999b297e9dceae610b1442dab8a262e078c3bf29e34603945a3fe425e824258e01"
      content-type: image/png
      signedUrl:
         timeToLive: 2
      image-ext: .png
      resource:
         profile: profilePicture/
         document: userDocument/
         settings: settingPicture/
      url: https://tima-resources.s3.us-east-2.amazonaws.com/
  accessKeyId: "{cipher}7308769c880d44773d73dbc0369c966b5ea54e55d14fb68603850fd544d8f5fda24410a25ac1c1b79739fb1c920647ca"
  secretKey: "{cipher}c24f4eff9cdfc4ec2a13177c0c1ee782fde0d456093eece3d3d8575ef30831999b297e9dceae610b1442dab8a262e078c3bf29e34603945a3fe425e824258e01"
#  sessionToken: ""
  region: us-east-2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    rabbit:
      enabled: true

